### PR TITLE
Update endpoints to return field errors

### PR DESCRIPTION
**Pull request by kwannoel**
Endpoints return `InvalidField` and `FormatErrors` to indicate invalid inputs.

### CODE REVIEW

**Comment by leyliramazanova** [comment]
were .env files updated for this?

**Comment by ivanleomk** [comment]
Add 

BACKEND_HOST=0.0.0.0
--


 to .env file

**Comment by ivanleomk** [comment]
Accidentally closed it

**Comment by kwannoel** [comment]
Both `.env` and `.env.local` have been updated

**Comment by leyliramazanova** [comment]
Just attempted to add a person with a term, but no relation and I got a message saying "Successful Query", but in the backend I am getting a DatabaseQueryError: Neo4jError: Invalid input.

**Comment by kwannoel** [comment]
> Just attempted to add a person with a term, but no relation and I got a message saying "Successful Query", but in the backend I am getting a DatabaseQueryError: Neo4jError: Invalid input.

@leyliramazanova not in scope of this PR, can you track it in a separate issue? This PR just exposes the errors.

**Comment by kwannoel** [comment]
> Just attempted to add a person with a term, but no relation and I got a message saying "Successful Query", but in the backend I am getting a DatabaseQueryError: Neo4jError: Invalid input.

Tracked in #152

**Pull request merged**
